<a href="https://colab.research.google.com/github/nikeshgamal24/Deep-Learning-with-PyTorch/blob/main/05.%20pytorch_training_pipeline_using_dataset_and_dataloader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### train test split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[-0.15192957, -0.67361089, -0.2079524 , ..., -0.43018358,
        -0.87984568, -0.18675875],
       [-1.38374745, -1.24113959, -1.32763698, ..., -0.95366882,
         0.65325694,  0.07048379],
       [ 0.13761795, -1.21367852,  0.23216638, ..., -0.05705634,
        -0.09200128,  0.4676884 ],
       ...,
       [-0.19053591, -1.50430814, -0.26871358, ..., -1.38409667,
        -1.00924216, -1.20079225],
       [-0.13814159, -0.73539829, -0.1827685 , ..., -0.6694099 ,
         0.72041208, -0.36599872],
       [-0.47456824, -0.45163394, -0.47817974, ..., -0.13934182,
         0.24868819, -0.38812711]])

In [9]:
y_train

51     B
63     B
421    B
333    B
437    B
      ..
124    B
551    B
308    B
374    B
497    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,

### Numpy arrays to PyTorch tensors

In [12]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [13]:
X_train_tensor.shape

torch.Size([455, 30])

In [14]:
y_train_tensor.shape

torch.Size([455])

In [15]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):

  def __init__(self,features,labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index] , self.labels[index]


In [16]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [17]:
train_dataset[10]

(tensor([-0.4553, -0.2777, -0.5194, -0.4661, -1.5148, -1.4484, -1.0847, -1.1006,
         -1.0092, -1.5279, -0.2049, -0.4654, -0.2675, -0.2687, -0.4079, -1.1529,
         -1.0022, -1.2945, -0.0064, -0.9920, -0.5257, -0.7379, -0.6040, -0.5136,
         -1.6735, -1.3353, -1.2773, -1.4701, -1.0649, -1.5720]),
 tensor(0.))

In [18]:
test_dataset[10]

(tensor([-0.4056, -1.2594, -0.4250, -0.4656,  0.0545, -0.3865, -0.9428, -0.7543,
         -0.6076, -0.2385, -0.7904, -0.9330, -0.7355, -0.5748, -0.3169, -0.7674,
         -0.8217, -0.6082, -0.8252, -0.8722, -0.5701, -1.2935, -0.5541, -0.5676,
         -0.0795, -0.6788, -1.0481, -0.7658, -0.8422, -0.7969]),
 tensor(0.))

In [24]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

In [26]:
i=0
for batch_feature, batch_label in train_loader:
  if i==0:
    print(batch_feature)
    print(batch_label)
    i +=1

tensor([[-1.3396e+00,  6.0791e-01, -1.3352e+00, -1.0878e+00, -2.4588e-01,
         -9.0203e-01, -6.1390e-01, -9.1546e-01, -4.1039e-01,  4.3223e-01,
         -3.7598e-01,  1.2031e+00, -3.6596e-01, -4.8288e-01,  1.2612e+00,
         -4.1266e-01,  2.2324e-01,  1.5387e-01,  2.0937e+00,  2.8740e-01,
         -1.3069e+00, -9.1957e-02, -1.2997e+00, -1.0029e+00, -9.2253e-01,
         -1.0845e+00, -9.1838e-01, -1.3311e+00, -7.3407e-01, -5.3639e-01],
        [-4.7733e-01,  1.0885e+00, -3.3747e-01, -5.0975e-01,  1.5971e+00,
          2.4919e+00,  1.6611e+00,  9.0782e-01,  8.2371e-01,  2.7813e+00,
         -3.8870e-01,  6.9875e-01, -4.0477e-01, -3.5816e-01,  3.4226e-02,
          2.5070e+00,  1.3956e+00,  3.8993e-01, -3.1729e-01,  2.2459e+00,
         -2.4951e-01,  2.3888e+00, -2.8956e-01, -3.0140e-01,  2.3198e+00,
          5.0743e+00,  3.9002e+00,  1.5916e+00,  2.4288e+00,  6.8528e+00],
        [-3.6702e-01, -1.3647e+00, -3.8344e-01, -4.3091e-01,  1.2313e+00,
         -3.0496e-01, -6.3771e-01, -

In [27]:
test_loader

### Defining the model

In [28]:
import torch.nn as nn


class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

### Important Parameters

In [41]:
learning_rate = 0.1
epochs = 25

In [42]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loss function
loss_function = nn.BCELoss()

### Training Pipeline

In [43]:

# define loop
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(batch_features)

    # loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1,1))

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.14240047335624695
Epoch: 2, Loss: 0.2875988781452179
Epoch: 3, Loss: 0.15335872769355774
Epoch: 4, Loss: 0.056366030126810074
Epoch: 5, Loss: 0.2709607183933258
Epoch: 6, Loss: 0.08103428035974503
Epoch: 7, Loss: 0.08117985725402832
Epoch: 8, Loss: 0.12186597287654877
Epoch: 9, Loss: 0.24038411676883698
Epoch: 10, Loss: 0.2093876451253891
Epoch: 11, Loss: 0.008560573682188988
Epoch: 12, Loss: 0.022961249575018883
Epoch: 13, Loss: 0.013867652043700218
Epoch: 14, Loss: 0.026883985847234726
Epoch: 15, Loss: 0.3400450646877289
Epoch: 16, Loss: 0.0368417389690876
Epoch: 17, Loss: 0.07106740027666092
Epoch: 18, Loss: 0.03671848401427269
Epoch: 19, Loss: 0.08368267118930817
Epoch: 20, Loss: 0.011553175747394562
Epoch: 21, Loss: 0.04006483405828476
Epoch: 22, Loss: 0.06270965188741684
Epoch: 23, Loss: 0.3391357362270355
Epoch: 24, Loss: 0.0950145497918129
Epoch: 25, Loss: 0.017285766080021858


### Evaluation

In [44]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')


Accuracy: 0.9705
